color: "#4f46e5"
copyright: "Copyright &copy; 2022 Acme Corporation. All Rights Reserved."
footer:
  - title: About
    content: >
        Acme Corporation is the world's leading 
        manufacturer of digital shapes. From squares and 
        circles to triangles and hexagons, we have it all.
        Browse through our collection of various forms with 
        different thicknesses and line styles. We shape 
        the world. You live in it.


  - title: Recent Blog Posts
    recents: blog
    recentCount: 7
  - title: Contact Us
    contact: true
style: blue
logo: /image/logo.png
logo_small: /image/logo.png
about_us: >
  Acme Corporation is the world's leading manufacturer 
  of digital shapes. From squares and circles to 
  triangles and hexagons, we have it all. Browse through 
  our collection of various forms with different 
  thicknesses and line styles. We shape the world. You 
  live in it.
recent_posts:
  enable: true
